arch: s390x
services:
  - docker
script: 
    docker build -t s390xdocker -f Dockerfile .
before_deploy:
    - docker tag  s390xdocker  "$DOCKER_USERNAME"/s390xdocker:latest
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin  
deploy:
  provider: script
  script: 
     docker push "$DOCKER_USERNAME"/s390xdocker:latest
  on:
    branch: master  
    
